# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Don Mizutani
tagline:          'Network Security Analyst. Software Developer. Test Automation Enthusiast.'
description:      'Network Security Analyst. Software Developer. Test Automation Enthusiast.'
url:              http://www.donmizutani.com
baseurl:          /

author:
  name:           'Don Mizutani'
  url:            https://twitter.com/donmizutani

paginate:         5

# Custom vars

# GitHub repo URL
github:
  repo:           https://github.com/donmizutani/donmizutani.github.io
